### ISSUE TITLE
network-firewall module data incorrectly referencing public subnetwork

### ISSUE THREAD

**Issue by billy-stem** [gruntwork-io/terraform-google-network#29]
Hey guys, I'm fairly sure this `data` config should reference `var.private_subnetwork` instead of `var.public_subnetwork`.

https://github.com/gruntwork-io/terraform-google-network/blob/4a90f39c6bd90b59d865c78068d7e9f1bf53f900/modules/network-firewall/main.tf#L6

**Comment by robmorgan** [comment]
Hi @billy-stem that does indeed look like a fairly silly mistake. I'll submit a PR.
