### ISSUE TITLE
SSH access? It's unclear.

### ISSUE THREAD

**Issue by dionjwa** [gruntwork-io/terraform-google-network#44]
It's not clear if private nodes can also have SSH access via `gcloud`. Guidance to how this would be enabled using this module?

**Comment by robmorgan** [comment]
hi @dionjwa, you can SSH into a private instance using a Bastion host if you've deployed one with [our module](https://github.com/gruntwork-io/terraform-google-network/tree/master/modules/bastion-host). Our instructions could be clearer, so I'll leave this issue open. For more information, you can also refer to [Google's documentation](https://cloud.google.com/compute/docs/instances/connecting-advanced#sshbetweeninstances).

**Comment by brianpham** [comment]
@dionjwa I am unsure about this as well. I have created a GKE cluster with private ips for the nodes with access only behind a VPN. I am trying to run `gcloud compute ssh --internal-ip` but running into a timeout error.

@robmorgan I have not tried but bastion host yet, but do you know if we should be able to ssh into the node using its private ip from vpn based on the current module?

**Comment by eak12913** [comment]
Closing per the message above
