### ISSUE TITLE
Error: "enable_flow_logs": [REMOVED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled. Please remove this field

### ISSUE THREAD

**Issue by captain-kark** [gruntwork-io/terraform-google-network#45]
Version 3.0.0 of the google cloud provider is removing this option.

https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_compute_subnetwork

**Comment by autero1** [comment]
Thanks for noting this @captain-kark . PR welcome!

**Comment by captain-kark** [comment]
I can start working on a couple of branches, I think it'll be worth it for me to move to 3.0.0 for everything I'm doing right now anyway.

What do you think about a couple of long running branches, for 2.x and 3.x?

**Comment by autero1** [comment]
Hi @captain-kark , would be great if can contribute! I don't think we need to create long-running branches - instead we just pin the providers in the examples to > 3.x.

**Comment by avielb** [comment]
please approve this

**Comment by robmorgan** [comment]
Released in https://github.com/gruntwork-io/terraform-google-network/releases/tag/v0.4.0
