### ISSUE TITLE
Question: Do instances in the public subnetwork have outbound access to the internet?

### ISSUE THREAD

**Issue by btomasini** [gruntwork-io/terraform-google-network#55]
As I understand it, instances on the public subnetwork are assigned internal addreses, but can be accessed from any routable addres via the 0.0.0.0/0 IP source on the firewall.

It also appears that the NAT router in the vpc_network module only NATs traffic from the private subnetwork.  Is this true? Does this mean that instances in the private subnetwork can access the Internet via the NAT and those on the public subnetwork cannot?

Guidance would be appreciated.

**Comment by btomasini** [comment]
Is it assumed that any instance in the public subnetwork will have a public IP address, and that is why there isn't any NAT on that subnetwork?

**Comment by rgreinho** [comment]
I have the exact same question. Looking at the code of the module itself, only the PRIVATE subnets can have outbound access (https://github.com/gruntwork-io/terraform-google-network/blob/master/modules/vpc-network/main.tf#L80). 

But the documentation states:
> public - instances are able to communicate over the public internet through Cloud NAT if an external IP was not provided
 
So maybe there is a trick to allow instances in the public subnet and without an external IP to access the internet?

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by MoonMoon1919** [comment]
Closing this issue per the sunset notice above.
