### ISSUE TITLE
Support for Terraform v0.15.x

### ISSUE THREAD

**Issue by brianpham** [gruntwork-io/terraform-google-network#63]
Seeing the following error when trying to use with Terraform v0.15.0

```
│ Error: Error in function call
│ 
│   on .terraform/modules/ucstaging_gke_cluster.vpc_network/modules/vpc-network/main.tf line 68, in resource "google_compute_subnetwork" "vpc_subnetwork_public":
│   68:     for_each = var.log_config == null ? [] : list(var.log_config)
│     ├────────────────
│     │ var.log_config is object with 3 attributes
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
╵
╷
│ Error: Error in function call
│ 
│   on .terraform/modules/ucstaging_gke_cluster.vpc_network/modules/vpc-network/main.tf line 124, in resource "google_compute_subnetwork" "vpc_subnetwork_private":
│  124:     for_each = var.log_config == null ? [] : list(var.log_config)
│     ├────────────────
│     │ var.log_config is object with 3 attributes
│ 
```

**Comment by robmorgan** [comment]
Hi @brianpham thanks for your issue. We have to properly support TF 0.14 first, then I imagine the upgrade to TF 0.15 will be slightly more difficult due to some of the language changes. e.g: `list` is deprecated as I can see above. I'll leave this issue open for now.

**Comment by eak12913** [comment]
Apologies for the delay in responding to this issue. Please see below:

Sunset notice
We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at [support@gruntwork.io](mailto:support@gruntwork.io).
