### ISSUE TITLE
Blocks of type "log_config" are not expected here

### ISSUE THREAD

**Issue by aivarastcloud** [gruntwork-io/terraform-google-network#73]
Terraform brings error when creating VPC with this module: Blocks of type "log_config" are not expected here
Used latest 0.8.2 version.
Terraform version: v1.0.2

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing this issue per the message above.
