### ISSUE TITLE
Why only 1 secondary range for private subnet?

### ISSUE THREAD

**Issue by tomasgareau** [gruntwork-io/terraform-google-network#76]
This pull request https://github.com/gruntwork-io/terraform-google-network/pull/64 added two secondary ranges to the `public` subnetwork for the `vpc-network` module...

https://github.com/gruntwork-io/terraform-google-network/blob/bb80cdcf0f06cf6d5adfbf6393e2ff641c66c4cb/modules/vpc-network/main.tf#L49-L65

... so that we can reference separate secondary ranges for the cluster & service ranges when setting up a GKE cluster. For example, using gruntwork's `terraform-google-gke` module:

```hcl
module "gke_cluster" {
  source = "github.com/gruntwork-io/terraform-google-gke.git//modules/gke-cluster?ref=v0.2.0"
  
  # ...project, region, etc...

  # the public subnetwork allows outbound internet access
  subnetwork                    = module.vpc_network.public_subnetwork
  cluster_secondary_range_name  = module.vpc_network.public_subnetwork_secondary_range_name
  services_secondary_range_name = module.vpc_network.public_services_secondary_range_name

  # ... more config ...
}
```

Is there a reason that there is not _also_ two secondary ranges for the `private` subnet? Say I wanted to create the cluster above, but in a private subnetwork (i.e., I do not want to allow nodes to access the internet):

```hcl
subnetwork                    = module.vpc_network.private_subnetwork
cluster_secondary_range_name  = module.vpc_network.private_subnetwork_secondary_range_name
services_secondary_range_name = module.vpc_network.private_services_secondary_range_name
```

won't work because the `vpc-network` module does _not_ create or output an equivalent to the `public_subnetwork_secondary_range_name` -- it only defines the "private-services" secondary range, not a "private-cluster" secondary range.

Is there a reason for this or was it an oversight in #64? I'm curious to learn if there's something I'm missing here or if this would be an unexpected use-case for some reason.

**Comment by eak12913** [comment]
Closing this issue per the message above.
