### ISSUE TITLE
Invalid Index Error

### ISSUE THREAD

**Issue by Rahulsharma0810** [gruntwork-io/terraform-google-network#78]
I am trying to use this module plan giving below error, any patch on this 

Version : 0.9.0

```
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_network/modules/network-firewall/main.tf line 86, in resource "google_compute_firewall" "private_allow_all_network_inbound":
│   86:     data.google_compute_subnetwork.public_subnetwork.secondary_ip_range[1].ip_cidr_range,
│     ├────────────────
│     │ data.google_compute_subnetwork.public_subnetwork.secondary_ip_range is list of object with 1 element
│
│ The given key does not identify an element in this collection value.
╵
```

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment]
Closing this issue per the message above.
